<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>xmake.lua</string>
        <string>xmake</string>
    </array>
    <key>name</key>
    <string>XMake</string>

    <!-- code folding -->
    <key>foldingStartMarker</key>
    <string>^\s*\b(function|local\s+function|if|for)\b|{[ \t]*$|\[\[</string>
    <key>foldingStopMarker</key>
    <string>\bend\b|^\s*}|\]\]</string>

    <key>patterns</key>
    <array>
        <!-- function headers -->
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.xmake</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.scope.xmake</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.xmake</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.parameters.begin.xmake</string>
                </dict>
                <key>5</key>
                <dict>
                    <key>name</key>
                    <string>variable.parameter.function.xmake</string>
                </dict>
                <key>6</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.parameters.end.xmake</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b(function)\s+([a-zA-Z_.:0-9]+[.:])?([a-zA-Z_]\w*)\s*(\()([^)]*)(\))</string>
            <key>name</key>
            <string>meta.function.xmake</string>
        </dict>
        <!-- Anonymous functions -->
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.control.xmake</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.parameters.begin.xmake</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>variable.parameter.function.xmake</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.parameters.end.xmake</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b(function)\s*(\()([^)]*)(\))</string>
            <key>name</key>
            <string>meta.function.xmake</string>
        </dict>
        <!-- Illegal comments -->
        <dict>
            <key>match</key>
            <string>\*/.*\n</string>
            <key>name</key>
            <string>invalid.illegal.stray-comment-end.xmake</string>
        </dict>
        <!-- hexadecemal/decimal constants -->
        <dict>
            <key>match</key>
            <string>\b0x[a-fA-F\d]+|\b\d+(\.\d+)?([eE]-?\d+)?|\.\d+([eE]-?\d+)?</string>
            <key>name</key>
            <string>constant.numeric.xmake</string>
        </dict>
        <!-- Single quoted strings -->
        <dict>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.xmake</string>
                </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.xmake</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.xmake</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\.</string>
                    <key>name</key>
                    <string>constant.character.escape.xmake</string>
                </dict>
            </array>
        </dict>
        <!-- Double quoted strings -->
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.xmake</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.xmake</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.xmake</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\.</string>
                    <key>name</key>
                    <string>constant.character.escape.xmake</string>
                </dict>
            </array>
        </dict>
        <!-- Multiline strings -->
        <dict>
            <key>begin</key>
            <string>(?&lt;!--)\[(=*)\[</string> <!-- negative lookbehind to not match multiline comments -->
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.xmake</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\]\1\]</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.xmake</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.other.multiline.xmake</string>
        </dict>
        <!-- Multiline comments (pure Lua) -->
        <dict>
            <key>begin</key>
            <string>--\[(=*)\[</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.xmake</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\]\1\]</string>
            <key>name</key>
            <string>comment.block.xmake</string>
        </dict>
        <!-- Multiline comments (Garry's Lua) -->
        <dict>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.xmake</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>name</key>
            <string>comment.block.xmake</string>
        </dict>
        <!-- Single line comment (pure Lua) -->
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.xmake</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(--)(?!\[\[).*$\n?</string>
            <key>name</key>
            <string>comment.line.double-dash.xmake</string>
        </dict>
        <!-- Single line comment (Garry's Lua) -->
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.xmake</string>
                </dict>
            </dict>
            <key>match</key>
            <string>(//)(?!\[\[).*$\n?</string>
            <key>name</key>
            <string>comment.line.double-slash.xmake</string>
        </dict>
        <!-- Control keywords -->
        <dict>
            <key>match</key>
            <string>\b(break|do|else|for|if|elseif|return|then|repeat|while|until|end|function|local|in|continue)\b</string>
            <key>name</key>
            <string>keyword.control.xmake</string>
        </dict>
        <!-- Important constants -->
        <dict>
            <key>match</key>
            <string>(?&lt;![^.]\.|:)\b(NULL|false|nil|true|_G|_R|_VERSION|self|math\.(pi|huge))\b|(?&lt;![.])\.{3}(?!\.)</string>
            <key>name</key>
            <string>constant.language.xmake</string>
        </dict>
        <!-- Operators -->
        <dict>
            <key>match</key>
            <string>\b(and|or|not)\b|\|\||&amp;&amp;|&amp;|\||\+|-|%|#|,|\{|\}|\[|\]|\*|\/|\^|==?|~=|!=|&lt;=?|&gt;=?|(?&lt;!\.)\.{2}(?!\.)</string>
            <key>name</key>
            <string>keyword.operator.xmake</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.xmake</string>
    <key>uuid</key>
    <string>4e20e032-26f9-424c-9850-970835861de8</string>
</dict>
</plist>